name: Build and Publish Docker Image

on:
  workflow_dispatch:
    inputs:
      tag:
        description: 'Image tag (default: v15)'
        required: false
        default: 'v15'
      frappe_branch:
        description: 'Frappe branch (default: version-15)'
        required: false
        default: 'version-15'
  push:
    branches: [ main ]
    paths:
      - 'apps.json'
      - 'scripts/build.sh'
      - 'frappe_docker/images/layered/Containerfile'
      - '.github/workflows/docker-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          submodules: 'recursive'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT

      - name: Build Docker image
        run: |
          chmod +x scripts/build.sh
          ./scripts/build.sh \
            --frappe-branch ${{ github.event.inputs.frappe_branch || 'version-15' }} \
            --image-name ghcr.io/${{ github.repository_owner }}/frappe-test \
            --image-tag ${{ github.event.inputs.tag || 'v15' }} \
            --platform linux/amd64

      - name: Push to GitHub Container Registry
        run: |
          # Push the versioned tag (e.g., v15-2023-04-17)
          docker push ghcr.io/${{ github.repository_owner }}/frappe-test:${{ github.event.inputs.tag || 'v15' }}-${{ steps.date.outputs.date }}

          # Push the latest tag (e.g., v15)
          docker push ghcr.io/${{ github.repository_owner }}/frappe-test:${{ github.event.inputs.tag || 'v15' }}
